name: 生成并混淆工作脚本

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  构建和混淆:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装混淆器
        run: npm install javascript-obfuscator

      - name: 从本地源文件进行混淆
        run: |
          node -e "
            const JavaScriptObfuscator = require('javascript-obfuscator');
            const fs = require('fs');
            const path = require('path');
            
            const sourceFileName = '明文源吗';
            const outputFileName = '少年你相信光吗';
            const sourceFilePath = path.join(process.cwd(), sourceFileName);

            if (!fs.existsSync(sourceFilePath)) {
              console.error(`错误：在路径 '$\{sourceFilePath\}' 未找到源文件。请确保您的仓库根目录有名为 '明文源吗' 的文件。`);
              process.exit(1);
            }

            const originalCode = fs.readFileSync(sourceFilePath, 'utf8');

            if (!originalCode || originalCode.trim().length === 0) {
              console.error('错误：源文件 ' + sourceFileName + ' 为空。');
              process.exit(1);
            }

            // --- 最终平衡型混淆配置 ---
            const obfuscationOptions = {
                compact: true,
                controlFlowFlattening: true,
                controlFlowFlatteningThreshold: 0.75,
                deadCodeInjection: true,
                deadCodeInjectionThreshold: 0.4,
                stringArray: true,
                stringArrayEncoding: ['base64'],
                stringArrayThreshold: 0.75,
                renameGlobals: true,
                identifierNamesGenerator: 'mangled',
                numbersToExpressions: true,
                splitStrings: true,
                splitStringsChunkLength: 10,
                transformObjectKeys: true,
                selfDefending: false,
                debugProtection: false
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync(path.join(process.cwd(), outputFileName), obfuscatedCode, 'utf8');
            console.log(`成功将 '$\{sourceFileName\}' 混淆并保存至 '$\{outputFileName\}'。`);
          "

      - name: 提交并推送混淆后的文件
        run: |
          git config --local user.name 'GitHub Actions Bot'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add '少年你相信光吗'
          if git diff --staged --quiet; then
            echo "没有更改需要提交，混淆文件已是最新版本。"
          else
            git commit -m "构建: 生成并混淆工作脚本"
            git push origin HEAD
          fi
