name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Obfuscator
        run: npm install javascript-obfuscator

      - name: Create source file and obfuscate
        run: |
          node -e "
            const JavaScriptObfuscator = require('javascript-obfuscator');
            const fs = require('fs');
            
            const originalCode = process.env.SOURCE_CODE;
            if (!originalCode || originalCode.length < 50) {
              console.error('Error: Source code from secrets is missing or empty.');
              process.exit(1);
            }

            const obfuscationOptions = {
                compact: true,
                minify: true,
                controlFlowFlattening: false,
                deadCodeInjection: false,
                stringArray: true,
                stringArrayEncoding: ['base64'],
                stringArrayThreshold: 0.8,
                renameGlobals: true,
                identifierNamesGenerator: 'mangled',
                transformObjectKeys: true,
                unicodeEscapeSequence: false,
                numbersToExpressions: true,
                splitStrings: true,
                splitStringsChunkLength: 10,
                selfDefending: false,
                debugProtection: false
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync('./少年你相信光吗', obfuscatedCode, 'utf8');
          "
        env:
          SOURCE_CODE: ${{ secrets.WORKER_SOURCE_CODE }}

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add '少年你相信光吗'
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "build: Generate and obfuscate worker script"
            git push
          fi            const obfuscationOptions = {
                compact: true,
                minify: true, // 启用代码压缩
                
                // 禁用最高消耗的功能
                controlFlowFlattening: false,
                deadCodeInjection: false,

                // 启用借鉴自新配置的高效保护功能
                stringArray: true,
                stringArrayEncoding: ['base64'],
                stringArrayThreshold: 0.8,
                
                renameGlobals: true, // 重命名全局变量
                identifierNamesGenerator: 'mangled', // 使用更短的混淆名称
                
                transformObjectKeys: true,
                unicodeEscapeSequence: false,
                
                // 新增：借鉴自新配置的轻量级混淆技术
                numbersToExpressions: true, // 数字转为表达式
                splitStrings: true, // 分割字符串
                splitStringsChunkLength: 10,
                
                // 禁用对性能有潜在影响的选项
                selfDefending: false,
                debugProtection: false
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync('./少年你相信光吗', obfuscatedCode, 'utf8');
          "
        env:
          SOURCE_CODE: ${{ secrets.WORKER_SOURCE_CODE }}

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add '少年你相信光吗'
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "build: Generate and obfuscate worker script"
            git push
          fi            const obfuscationOptions = {
                compact: true,
                // 已禁用：以下是导致 CPU 超时的主要原因
                controlFlowFlattening: false,
                deadCodeInjection: false,
                debugProtection: false,
                selfDefending: false,

                // 依然保留的核心保护功能
                disableConsoleOutput: true,
                identifierNamesGenerator: 'hexadecimal',
                renameGlobals: true,
                stringArray: true,
                stringArrayEncoding: ['base64'],
                stringArrayThreshold: 1, // 100% 的字符串都将被隐藏
                transformObjectKeys: true,
                unicodeEscapeSequence: false
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync('./少年你相信光吗', obfuscatedCode, 'utf8');
          "
        env:
          SOURCE_CODE: ${{ secrets.WORKER_SOURCE_CODE }}

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add '少年你相信光吗'
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "build: Generate and obfuscate worker script"
            git push
          fi
